# Generated by Django 6.1 on 2026-09-20 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(help_text="Votre nom d'affichage unique dans les jeux.", max_length=30, unique=True, verbose_name='Pseudonyme')),
                ('bio', models.TextField(blank=True, help_text='Décrivez-vous en quelques mots.', max_length=160, verbose_name='Biographie')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='Parties jouées')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Victoires')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Défaites')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['pseudonym'],
            },
        ),
    ]
