# Generated by Django 6.1 on 2026-09-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeu',
            options={'verbose_name': 'jeu', 'verbose_name_plural': 'jeux'},
        ),
    ]
