# Generated by Django 6.1.1 on 2026-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_jeu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='slug',
            field=models.SlugField(default='premier-clic', unique=True),
            preserve_default=False,
        ),
    ]
